[package]
name = "ordermap"
version = "0.1.1"
authors = ["bluss"]
documentation = "https://docs.rs/ordermap/0.1/"
repository = "https://github.com/bluss/ordermap"
license = "Apache-2.0/MIT"
description = "A hash table with consistent order and fast iteration."

[dependencies]

[dev-dependencies]
itertools = "0.4"
rand = "0.3"
quickcheck = "0.3.1"
fnv = "1.0"
lazy_static = "0.2"

[profile.bench]
debug = true
